### ISSUE TITLE
Updated questions 2022 to technician questions

### ISSUE THREAD

**Issue by spasticninja** [russolsen/ham_radio_question_pool#1]
Hi! Thanks for including this test bank. I would love to use it, but want to incorporate the most recent updates from 2022 

[The PDF with the updates](http://ncvec.org/downloads/Technician%20Pool%20and%20Syllabus%202022-2026%20Public%20Release%20Errata%20March%207%202022.pdf). Here is the summary:

## Modification of Public Release issued on March 7, 2022
4 Question Modifications:
T2A09 –replaced station’s with repeater’s in answer A to read:
A. “CQ CQ” followed by the repeater’s call sign
T2B12 - replaced answer A to read:
A. Must match the repeater color code for access
T6B07 remove DC in answers A and B
T8D02 replaced digital with DMR before repeater in the question to read:
What is a Talkgroup on a DMR repeater?
2022-2026 Technician Class Question Pool Errata

The following changes have been made to the posted 
2022-2026 Technician Class FCC Element 2 Question Pool

## Released on January 17, 2022
Modification of Public Release issued on January 17, 2022
1 Question Deletion:
T7D05 withdrawn from use
The remaining questions in T7D were not renumbered

## Modification of Public Release issued on January 6, 2022
5 Question Modifications:
T4A07 replaced : (semi-colon) with . (period) in distractors
T5C08, T5D01, T5D02, T5DO3 reverted ‘V’ to ‘E’

**Comment by IanDuncanT** [comment]
The new question pools are available at https://github.com/W5AC-TAMU/exam-question-pool
